services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8081:8080"
    volumes:
      - "./mock-server/mappings:/home/wiremock/mappings"
    command: --verbose --global-response-templating